#!/bin/sh

escaper() {
    sed 's/[&/\]/\\&/g'
}

srcdir="$HOME/.local/state/xpet/baby"
outdir="$HOME/.cache/wal/xbaby"
walcol="$HOME/.cache/wal/colors.baby"

line5="$(sed -n 1p "$walcol" | escaper)"
line6="$(sed -n 2p "$walcol" | escaper)"
line7="$(sed -n 3p "$walcol" | escaper)"
line8="$(sed -n 4p "$walcol" | escaper)"

find "$srcdir" -type f -name '*.xpm' | while IFS= read -r file; do
    rel="${file#$srcdir/}"
    out="$outdir/$rel"
    mkdir -p "$(dirname "$out")"
    sed "5s|.*|$line5|; 6s|.*|$line6|; 7s|.*|$line7|; 8s|.*|$line8|" "$file" > "$out"
done
